### ISSUE TITLE
Error when trying to resolve dependency with null values

### ISSUE THREAD

**Issue by jkerr5** [ysb33r/ivypot-gradle-plugin#21]
I'm not sure where this dependency is coming from but the ivypot plugin is throwing an error while trying to resolve a null dependency. This is the error:

```
:syncRemoteRepositories
[syncRemoteRepositoriesConfigure] :: Ivy 2.2.0 - 20100923230623 :: http://ant.apache.org/ivy/ ::
[syncRemoteRepositoriesConfigure] :: loading settings :: file = /root/projects/cognizant-ipas/ML_DHF_IPAS/build/tmp/syncRemoteRepositories/ivysettings.xml
[syncRemoteRepositoriesResolve] ivy.instance reference an ivy:settings defined in an other classloader.  An new default one will be used in this project.
[syncRemoteRepositoriesResolve] :: problems summary ::
[syncRemoteRepositoriesResolve] :::: WARNINGS
[syncRemoteRepositoriesResolve]                 module not found: null#unspecified;null
[syncRemoteRepositoriesResolve]         ==== BintrayJCenter: tried
[syncRemoteRepositoriesResolve]           https://jcenter.bintray.com/null/unspecified/null/unspecified-null.pom
[syncRemoteRepositoriesResolve]           -- artifact null#unspecified;null!unspecified.jar:
[syncRemoteRepositoriesResolve]           https://jcenter.bintray.com/null/unspecified/null/unspecified-null.jar
[syncRemoteRepositoriesResolve]         ==== MavenRepo: tried
[syncRemoteRepositoriesResolve]           http://repo1.maven.org/maven2/null/unspecified/null/unspecified-null.pom
[syncRemoteRepositoriesResolve]           -- artifact null#unspecified;null!unspecified.jar:
[syncRemoteRepositoriesResolve]           http://repo1.maven.org/maven2/null/unspecified/null/unspecified-null.jar
[syncRemoteRepositoriesResolve]         ==== maven: tried
[syncRemoteRepositoriesResolve]           https://plugins.gradle.org/m2/null/unspecified/null/unspecified-null.pom
[syncRemoteRepositoriesResolve]           -- artifact null#unspecified;null!unspecified.jar:
[syncRemoteRepositoriesResolve]           https://plugins.gradle.org/m2/null/unspecified/null/unspecified-null.jar
[syncRemoteRepositoriesResolve]         ==== maven2: tried
[syncRemoteRepositoriesResolve]           http://developer.marklogic.com/maven2/null/unspecified/null/unspecified-null.pom
[syncRemoteRepositoriesResolve]           -- artifact null#unspecified;null!unspecified.jar:
[syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
[syncRemoteRepositoriesResolve]                 ::          UNRESOLVED DEPENDENCIES         ::
[syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
[syncRemoteRepositoriesResolve]                 :: null#unspecified;null: not found
[syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
:syncRemoteRepositories FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':syncRemoteRepositories'.
> impossible to resolve dependencies:
        resolve failed - see output for details

```

This it the exception
```
Caused by: : impossible to resolve dependencies:
        resolve failed - see output for details
        at org.apache.ivy.ant.IvyResolve.doExecute(IvyResolve.java:318)
        at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:277)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.ysb33r.gradle.ivypot.OfflineRepositorySync.ivyInstall(OfflineRepositorySync.groovy:208)
        at org.ysb33r.gradle.ivypot.OfflineRepositorySync$_exec_closure4.doCall(OfflineRepositorySync.groovy:193)
        at org.ysb33r.gradle.ivypot.OfflineRepositorySync.exec(OfflineRepositorySync.groovy:192)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: resolve failed - see output for details
        at org.apache.ivy.ant.IvyResolve.doExecute(IvyResolve.java:251)
        ... 82 more

```

**Comment by ysb33r** [comment]
Will try to have a look this weekend.


Sent from my Samsung device

-------- Original message --------

**Comment by ysb33r** [comment]
I cannto reproduce this. Do you have an example project I can check?

**Comment by tr7zw** [comment]
I am faceing the same issue where all dependencies have "null" as version. For me this happens when I have a parent project defining dependency constraints for the subprojects, and the subprojects have their dependencies without version. Seems like ivypot isn't able to use the constraints.

**Comment by ysb33r** [comment]
If you can provide me with an example project, then I can see what can be done to solve this issue.

**Comment by tr7zw** [comment]
https://gist.github.com/tr7zw/debb0758e68dcc107024c361c7440503 quickly created 2 build.gradle files that have this problem.
gradle dependencies output:

> compileClasspath - Compile classpath for source set 'main'.
> +--- org.projectlombok:lombok -> 1.18.10
> \--- org.projectlombok:lombok:1.18.10 (c)

gradle syncRemoteRepositories output:

> [syncRemoteRepositoriesConfigure] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
> [syncRemoteRepositoriesConfigure] :: loading settings :: file = ...\gradletest\subproject\build\tmp\syncRemoteRepositories\ivysettings.xml
> [syncRemoteRepositoriesResolve] ivy.instance reference an ivy:settings defined in an other classloader.  An new default one will be used in this project.
> [syncRemoteRepositoriesResolve] :: problems summary ::
> [syncRemoteRepositoriesResolve] :::: WARNINGS
> [syncRemoteRepositoriesResolve]                 module not found: org.projectlombok#lombok;null
> [syncRemoteRepositoriesResolve]         ==== MavenLocal: tried
> [syncRemoteRepositoriesResolve]           file:/.../.m2/repository/org/projectlombok/lombok/null/lombok-null.pom
> [syncRemoteRepositoriesResolve]           -- artifact org.projectlombok#lombok;null!lombok.jar:
> [syncRemoteRepositoriesResolve]           file:/.../.m2/repository/org/projectlombok/lombok/null/lombok-null.jar
> [syncRemoteRepositoriesResolve]         ==== MavenRepo: tried
> [syncRemoteRepositoriesResolve]           http://repo1.maven.org/maven2/org/projectlombok/lombok/null/lombok-null.pom
> [syncRemoteRepositoriesResolve]           -- artifact org.projectlombok#lombok;null!lombok.jar:
> [syncRemoteRepositoriesResolve]           http://repo1.maven.org/maven2/org/projectlombok/lombok/null/lombok-null.jar
> [syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
> [syncRemoteRepositoriesResolve]                 ::          UNRESOLVED DEPENDENCIES         ::
> [syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
> [syncRemoteRepositoriesResolve]                 :: org.projectlombok#lombok;null: not found
> [syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
> [syncRemoteRepositoriesResolve]
> [syncRemoteRepositoriesResolve] :::: ERRORS
> [syncRemoteRepositoriesResolve]         Server access Error: Connection timed out: connect url=http://repo1.maven.org/maven2/org/projectlombok/lombok/null/lombok-null.pom
> [syncRemoteRepositoriesResolve]         Server access Error: Connection timed out: connect url=http://repo1.maven.org/maven2/org/projectlombok/lombok/null/lombok-null.jar

For my current project I was able to use ivy directly in order to resolve and create the ivy cache that I needed, but getting this fixed is probably helpfull for future projects.

**Comment by ysb33r** [comment]
Thank you. This will help, I'm sure/

**Comment by jensborrmann** [comment]
Did you manage to have a first look into this issue. We are running into it as well.

**Comment by ysb33r** [comment]
@tr7zw Thank you for your example. I have managed to repoduce the issue within a test.

@jensborrmann FInally got some time to look at this.

**PLEASE NOTE*: The repo has moved here https://gitlab.com/ysb33rOrg/ivypot-gradle-plugin
