### ISSUE TITLE
Crash in gradle 6.0.1 during configuration

### ISSUE THREAD

**Issue by DALDEI** [ysb33r/ivypot-gradle-plugin#44]
Running under gradle 6.0.1 generates exception during configuration:

`2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.UnsupportedOperationException
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java_util_Map$put.call(Unknown Source)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.ysb33r.gradle.ivypot.OfflineRepositorySync.<init>(OfflineRepositorySync.groovy:61)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.ysb33r.gradle.ivypot.OfflineRepositorySync_Decorated.<init>(Unknown Source)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:200)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:402)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:55)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:72)
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 169 more
2019-12-08T11:36:12.744-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
`

this is caused by the following:
   inputs.properties.put( ... )

Guess:  inputs.properties is no longer a writable map

**Comment by ysb33r** [comment]
Fixed for 0.11
